export type TableNames = 
  | "invoiceTable" 
  | "paymentTransactions" 
  | "customerMaster" 
  | "user_profiles" 
  | "user_management"
  | "dashboard_metrics"
  | "whatsapp_config"
  | "role_permissions"
  | "feature_permissions"
  | "custom_permissions"
  | "dashboard_layouts"
  | "financial_year_ranges"
  | "customer_ledger"
  | "invoice_reminder_status";